openapi: 3.0.0
info:
  version: 2.0.0
  title: Sample API v2
  description: Better sample description
  contact:
    email: jack.tysoe@konghq.com

servers:
- url: http://echo-server.kong.svc.cluster.local:8080/v2

tags:
  - name: list

paths:
  /v2/list:
    get:
      description: Returns a list of stuff v2
      operationId: list
      tags:
      - list
      responses:
        '200':
          description: Successful response
