openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API v1
  description: Better sample description
  contact:
    email: jack.tysoe@konghq.com

servers:
- url: http://echo-server.kong.svc.cluster.local:8080/v1

tags:
  - name: list

paths:
  /v1/list:
    get:
      description: Returns a list of stuff v1        
      operationId: list
      tags:
      - list
      responses:
        '200':
          description: Successful response
